CHeck that the required Rio environment exists prior to trying to install or start any services

diff --git a/bin/rio b/bin/rio
--- a/bin/rio
+++ b/bin/rio
@@ -81,9 +81,14 @@ toWindows() {
 
 # Call the install script, do not assume that Groovy has been installed.
 installRioToLocalRepository() {
-    groovyClasspath="-cp `toNative $RIO_LIB/groovy-all.jar`"
-    ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
-    $scriptDir/install.groovy $JAVA_HOME $RIO_HOME
+    if [ -f "$RIO_LIB" ]; then
+        groovyClasspath="-cp `toNative $RIO_LIB/groovy-all.jar`"
+        ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
+        $scriptDir/install.groovy $JAVA_HOME $RIO_HOME
+    else
+        echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
+        exit 1
+    fi
 }
 
 #DEBUG=-Dorg.rioproject.tools.webster.debug
