Always call installer

diff --git a/bin/rio b/bin/rio
--- a/bin/rio
+++ b/bin/rio
@@ -104,15 +104,13 @@ riverVersion=@riverV@
 
 # Call the install script, do not assume that Groovy has been installed.
 installRioToLocalRepository() {
-    if [ ! -f "$RIO_HOME/logs/install.log" ]; then
-        if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
-            groovyClasspath="-cp $(toNative $RIO_LIB/groovy-all-$groovyVersion.jar)"
-            """$JAVACMD""" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
-            $scriptDir/install.groovy $JAVA_HOME "$(toNative $RIO_HOME)"
-        else
-            echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
-            exit 1
-        fi
+    if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
+        groovyClasspath="-cp $(toNative $RIO_LIB/groovy-all-$groovyVersion.jar)"
+        """$JAVACMD""" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
+        "$scriptDir"/install.groovy "$JAVA_HOME" "$(toNative "$RIO_HOME")"
+    else
+        echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
+        exit 1
     fi
 }
 
@@ -149,6 +147,8 @@ fi
 # If the command is to start the Rio services, invoke the ServiceStarter
 # Otherwise invoke the CLI
 if [ "$start" = "1" ]; then
+    installRioToLocalRepository
+
     if [ -z "$RIO_NATIVE_DIR" ] ; then
         RIO_NATIVE_DIR="$(toNative $RIO_LIB/native)"
     fi
