Remove log setup management from AgentHook and put into LogManagementHelper, and do not start the JVM using instrumentation by default

diff --git a/bin/rio b/bin/rio
--- a/bin/rio
+++ b/bin/rio
@@ -50,7 +50,6 @@ fi
 RIO_HOME=`cd "$RIO_HOME" && pwd`
 
 RIO_LIB=$RIO_HOME/lib
-RIO_LIB_DL=$RIO_HOME/lib-dl
 
 # Check for JAVA_HOME
 if [ -z "$JAVA_HOME" ] ; then
@@ -101,13 +100,15 @@ groovyVersion=2.1.3
 
 # Call the install script, do not assume that Groovy has been installed.
 installRioToLocalRepository() {
-    if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
-        groovyClasspath="-cp `toNative $RIO_LIB/groovy-all-$groovyVersion.jar`"
-        ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
-        $scriptDir/install.groovy $JAVA_HOME $RIO_HOME
-    else
-        echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
-        exit 1
+    if [ ! -f "$RIO_HOME/logs/install.log" ]; then
+        if [ -f "$RIO_LIB/groovy-all-$groovyVersion.jar" ]; then
+            groovyClasspath="-cp `toNative $RIO_LIB/groovy-all-$groovyVersion.jar`"
+            ""$JAVACMD"" $groovyClasspath org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain \
+            $scriptDir/install.groovy $JAVA_HOME $RIO_HOME
+        else
+            echo "The required Rio environment does not exist, it seems either that the configured or derived setting of RIO_HOME [$RIO_HOME] is invalid."
+            exit 1
+        fi
     fi
 }
 
@@ -206,7 +207,7 @@ if [ "$start" = "1" ]; then
         -XX:+HeapDumpOnOutOfMemoryError \
         -XX:OnOutOfMemoryError="$RIO_HOME/bin/rio restart %p $service" \
         -XX:HeapDumpPath=$RIO_HOME/logs \
-        $classpath $agentpath $libpath $RIO_OPTS \
+        $classpath $libpath $RIO_OPTS \
         -Djava.security.policy=$RIO_HOME/policy/policy.all \
         -Djava.protocol.handler.pkgs=org.rioproject.url \
         $loggingConfig \
